stan-dev/bayesplot

vignettes/MCMC-diagnostics.Rmd
vignettes/MCMC.Rmd
vignettes/PPC.Rmd

The figures are not showing up in the CRAN vignettes. 
If you need both pdf and png output, try using a vector with `c("png", "pdf")` in the `dev` option.

use png for html vignette figures

---

NEWS.md
R/bayesplot-helpers.R
tests/testthat/test-convenience-functions.R

`xaxis_title(FALSE)` and `yaxis_title(FALSE)` now set axis titles to `NULL` rather than changing theme elements to `element_blank`. This makes it easier to add axis titles to plots that don’t have them by default.

Axis title functions without element blank

---

NEWS.md
R/helpers-mcmc.R
R/mcmc-intervals.R
man-roxygen/args-transformations.R
man/MCMC-distributions.Rd
man/MCMC-intervals.Rd
man/MCMC-scatterplots.Rd
man/MCMC-traces.Rd
tests/testthat/test-helpers-mcmc.R

Resolves #64 
If the `transformations` argument is specified as a single function object or string naming a function then that transformation will be applied to all parameters. If specified as a named list then the behavior is the same as before. 
-----------------
```r
x <- example_mcmc_draws()
mcmc_intervals(x, regex_pars = "beta", transformations = "exp")
mcmc_intervals(x, regex_pars = "beta", transformations = exp) 
```

Allow recycling transformations

---

R/mcmc-recover.R

As discussed in my original feature request.
This adds a an example to the mcmc recover intervals page which shows how one can quickly get a bias plot which is simply a centering by the true values. I do find this plot much easier to read. However, the bias has to be understood in the context of a prior being present which may be visible or not depending on the amount of data relative to the prior.

add bias plot example to mcmc recover intervals

---

R/ppc-distributions.R
man/PPC-distributions.Rd

I plotted a reaction time analysis using ppc_violin_grouped and got this:
However, I personally find this plot more informative as it shows the density of the empirical data also:
I created a pull request to deliver the solution to my problem instead of just opening an issue and `complaining`. Possibly, however, there are reasons out of my knowledge why the data is plotted as `geom_point` and not `geom_violin`. 
I'm also not sure about any possible conventions regarding the plotting style of data. I found the current style easy to see for my example.

ppc_violin_grouped: plot y as violin, too

---

R/helpers-mcmc.R

Small change, previously I was able to use `mcmc` objects from `coda` with `bayesplot`, but due to the change of `parameter_names` into S3 method, this is no longer possible, as there are only methods for objects of class `matrix` and `array`. As `mcmc` object is basically vector or matrix, the matrix method should be applicable to `mcmc` objects as well (in matrix case). And there are perhaps other similar cases. So I changed the `parameter_names.matrix` to default method, which shouldn't break anything but makes the method and an all the function which use it more robust.

Convert parameter_names.matrix to parameter_names.default

---

vignettes/PPC.Rmd

fixed Predictive Posterior Checks vignette so that tildes used to indicating new data are centered over the variable - regular "\tilde" renders like a superscript on the right whereas "\widetilde" is larger and centered directly over the variable.

change tilde to widetilde

---

R/helpers-ppc.R

As discussed in #92, small modifications to `validate_y` and `validate_x` so that they also accept univariate `ts` objects.

validate ts

---

NEWS.md
R/bayesplot-ggplot-themes.R
R/helpers-gg.R
R/mcmc-alg-nuts.R
R/mcmc-diagnostics.R
R/mcmc-distributions.R
R/mcmc-intervals.R
R/mcmc-recover.R
R/mcmc-scatterplots.R
R/mcmc-traces.R
R/ppc-discrete.R
R/ppc-distributions.R
R/ppc-errors.R
R/ppc-intervals.R
R/ppc-loo.R
R/ppc-scatterplots.R
R/ppc-test-statistics.R
R/zzz.R
man/theme_default.Rd

Set `theme_default()` as the default ggplot theme when loading __bayesplot__ instead of hardcoding it in each function. This makes changing the theme using `ggplot2::theme_set` possible.
See issue #87 for details.

Optional plot theme

---

.travis.yml
DESCRIPTION

Now that testthat v2.0.0 is on CRAN (and the bug in test_path is fixed) this PR adds testthat (>= 2.0.0) to DESCRIPTION and removes it from r_github_packages in the travis file. It also replaces jimhester/covr with r-lib/covr.

Update testthat and covr in .travis.yml

---

NEWS.md
R/mcmc-diagnostics-nuts.R
R/mcmc-diagnostics.R
R/mcmc-distributions.R
R/mcmc-recover.R
R/ppc-distributions.R
R/ppc-errors.R
R/ppc-test-statistics.R
man-roxygen/args-hist.R
man-roxygen/args-transformations.R
man/MCMC-diagnostics.Rd
man/MCMC-distributions.Rd
man/MCMC-intervals.Rd
man/MCMC-nuts.Rd
man/MCMC-parcoord.Rd
man/MCMC-recover.Rd
man/MCMC-scatterplots.Rd
man/MCMC-traces.Rd
man/PPC-distributions.Rd
man/PPC-errors.Rd
man/PPC-test-statistics.Rd

This PR just adds a `breaks` argument to histograms that can be used as an alternative to `binwidth`. Turns out to be useful sometimes.

Pass 'breaks' to geom_histogram

---

NEWS.md
R/ppc-loo.R

This pull request fixes #166. The problems are described in that issue, and the diagnosis of the problems and their fixes are described there too. This pull request also the following warnings raised by testthat
```
test-ppc-loo.R:32: warning: ppc_loo_pit_overlay returns ggplot object
no non-missing arguments to min; returning Inf
test-ppc-loo.R:32: warning: ppc_loo_pit_overlay returns ggplot object
no non-missing arguments to max; returning -Inf
```
I don't know have a good statistical sense of what PIT is, and I didn't have any reference images for what these plots are supposed to look in general, so I would like @jgabry to review the changes here.

fix ppc_loo_pit_overlay() and ppc_loo_pit_qq()

---

R/bayesplot-helpers.R

This (finally) adds an example to the documentation that shows how to change the facet labels via `facet_relabel_gg()` of a grouped PPC plot, as discussed in https://github.com/stan-dev/bayesplot/issues/75.

add grouped PPC example for facet_relabel_gg

---

NEWS.md
R/helpers-mcmc.R
R/mcmc-overview.R
man-roxygen/args-mcmc-x.R
man/MCMC-combos.Rd
man/MCMC-diagnostics.Rd
man/MCMC-distributions.Rd
man/MCMC-intervals.Rd
man/MCMC-overview.Rd
man/MCMC-parcoord.Rd
man/MCMC-recover.Rd
man/MCMC-scatterplots.Rd
man/MCMC-traces.Rd
man/PPC-discrete.Rd
tests/testthat/test-helpers-mcmc.R

Closes #175.
As suggested by @bgoodri, with this PR objects with as.array methods can now be passed to the MCMC plots (not the PPC plots) without the user having to call as.array. For example, 
```r
fit <- stan_glm(mpg ~ wt, data = mtcars)
mcmc_hist(fit)
mcmc_hist(as.array(fit))
```
If the resulting array doesn't have 2 or 3 dimensions an error is thrown.

Call as.array on input to prepare_mcmc_array()

---

DESCRIPTION
NEWS.md
R/bayesplot-colors.R
R/bayesplot-ggplot-themes.R
man-roxygen/seealso-theme.R
man/bayesplot-colors.Rd
man/bayesplot-package.Rd
man/theme_default.Rd
tests/figs/aesthetics/color-scheme-view-brewer-palette.svg
tests/figs/aesthetics/color-scheme-view-default.svg
tests/figs/aesthetics/color-scheme-view-mixed-scheme.svg
tests/figs/aesthetics/color-scheme-view-scheme-specified.svg
tests/testthat/test-aesthetics.R

Closes #177 
This PR allows ColorBrewer palettes to be used with `bayesplot::color_scheme_set()`. 
Basically,  if a user specifies `color_scheme_set("brewer-X")`, where `X` is the name of a ColorBrewer palette recognized by **RColorBrewer**, then **bayesplot** will use  `RColorBrewer::brewer.pal(n = 6, name="X")` to get the colors. 
I also cleaned up and rearranged some internals in the `bayesplot-colors.R` file and changed the roxygen to use markdown, so it may seem like more changed than actually did. The only change that changes any behavior is in these lines in the internal `scheme_from_string()` function: 
https://github.com/stan-dev/bayesplot/blob/ac6f8ae78a9018f50b3353783c91f77f659a06e6/R/bayesplot-colors.R#L251-L258
```r
color_scheme_set("brewer-Spectral") …
```

Add ColorBrewer palettes

---

NEWS.md
R/mcmc-intervals.R
R/mcmc-traces.R
man/MCMC-traces.Rd
tests/testthat/test-mcmc-intervals.R

The rank-normalization paper says:
> Rank normalization proceeds as follows. First, replace each value θ^(nm) by its rank r^(nm) within the pooled draws from all chains. Average rank for ties are used to conserve the number of unique values of discrete quantities.
I was breaking ties by using `dplyr::row_number()` which works like `rank(.., ties.method = "first")`. This update changes the method to use averages.
It also fixes a warning from the unit tests.

Rank hotfix

---

R/helpers-mcmc.R
tests/testthat/test-helpers-mcmc.R

This is the simplest way I could think for fixing #160. All existing (non-visual) tests pass.

Avoid warning when using tibbles (fixes #160)

---

R/available-module-functions.R

The behavior is unaltered, but Rstudio now does not warn about a missing argument.

Default value in available_ppc()/available_mcmc()

---

NEWS.md
R/mcmc-intervals.R
man/MCMC-intervals.Rd
tests/figs/mcmc-intervals/mcmc-intervals-sizes.svg
tests/testthat/test-mcmc-intervals.R

Closes #215 and #228 
This PR adds the arguments `inner_size`, `outer_size`, and `point_size` to `mcmc_intervals()` to control the size (thickness) of the interval segments and the size of the point estimate. 
Also adds one new vdiffr visual test.

control sizes of intervals and points in mcmc_intervals 

---

NEWS.md
R/ppc-loo.R
man/PPC-loo.Rd
tests/testthat/test-ppc-loo.R

This fixes #240. Notes:
* I have updated the documentation as well as possible. But I might have missed some places in the documentation which need to get updated, too.
* I have moved two lines of code in "tests/testthat/test-ppc-loo.R" which I think got misplaced.

Fix y axis for ppc_loo_pit_qq() with 'compare = "normal"'

---

NEWS.md
R/mcmc-diagnostics.R

Closes #245 (tests pass locally for me)

Use melt_mcmc instead of calling reshape2::melt

---

tests/testthat/test-ppc-distributions.R

While working on a different PR, I noticed that I do not have ggfortify installed and tests failed because of that.  This PR skips those tests when ggfortify is not installed.

Require ggfortify for some tests

---

.gitignore
DESCRIPTION
NEWS.md
R/helpers-mcmc.R
R/mcmc-overview.R
man-roxygen/args-mcmc-x.R
man/MCMC-combos.Rd
man/MCMC-diagnostics.Rd
man/MCMC-distributions.Rd
man/MCMC-intervals.Rd
man/MCMC-overview.Rd
man/MCMC-parcoord.Rd
man/MCMC-recover.Rd
man/MCMC-scatterplots.Rd
man/MCMC-traces.Rd
tests/testthat/data-for-mcmc-tests.R
tests/testthat/test-mcmc-combo.R
tests/testthat/test-mcmc-distributions.R
tests/testthat/test-mcmc-scatter-and-parcoord.R

Closes #274 
Provides the flexibility to use all [posterior](https://github.com/stan-dev/posterior) `draws` objects as inputs to plotting functions by casting them to `draws_array` within `prepare_mcmc_array()`.

handle posterior's draws objects

---

R/bayesplot-ggplot-themes.R
R/bayesplot-helpers.R
R/mcmc-diagnostics.R
R/mcmc-distributions.R
R/mcmc-traces.R
R/ppc-errors.R
tests/testthat/test-convenience-functions.R

Hello there,
We have been preparing a new release of ggplot2 and during a reverse dependency check, it became apparent that the prospective ggplot2 3.5.0 would break bayesplot.
This PR updates the `legend_move()` function to deal with the incoming changes.
Additionally, it removes the deprecated use of `legend.text.align` and `facet_grid(facet = ...)`.
To test the code changes with the release candidate, you can install it with the code below:
```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```
The release of ggplot2 3.5.0 is scheduled for the 12th of February. The progress of the release can be tracked in https://github.com/tidyverse/ggplot2/issues/5588. We hope that this PR might help bayesplot get out a fix if necessary.

Update for new ggplot2 release

---

R/ppc-loo.R
tests/testthat/_snaps/ppc-loo/ppc-loo-pit-qq-default.svg

EDIT: fixes #296 
loo_pit_qq plots were using geom_qq + geom_qq_line, but that line was not useful in these plots. geom_qq_line is useful if the mean and scale of the data can be different and only the shape matters. When plotting PITs, they are constrained in range [0,1] and the qq's should follow the diagonal. When plotting with `compare='normal'`, the reference line should stiill be diagonal. This PR fixes the line and sets axis limit for the uniform qq-plot to be (0,1). Examples of old and new plots
Old uniform, as the line is diagonal it makes it more difficult to see the relevant difference:
New uniform:
Old normal:
New normal:

better loo_pit_qq plots

---

R/mcmc-intervals.R

Setting `prob <- FALSE`, e.g. in `mcmc_intervals`, does not raise an error but has unintended consequences.

Check intervals numeric

---

R/mcmc-diagnostics-nuts.R
R/mcmc-scatterplots.R
R/ppc-distributions.R
R/ppc-errors.R
R/ppc-test-statistics.R
R/ppd-distributions.R
R/ppd-test-statistics.R
man/MCMC-nuts.Rd
man/MCMC-scatterplots.Rd
man/PPC-distributions.Rd
man/PPC-errors.Rd
man/PPC-test-statistics.Rd
man/PPD-distributions.Rd
man/PPD-test-statistics.Rd

This is a follow-up of #285 and #300.

Add `bins` and `breaks` arguments to more histogram and hex plots

---

R/mcmc-intervals.R
R/mcmc-parcoord.R
R/mcmc-traces.R

This is a follow-up of f38d0639ead5f13d0a92178669b112cbbb3fe625 and 89c12289379f87c8d7e4fbcaecf079fc75399ba2.

Replace size argument with linewidth for geom_line and geom_ridgeline

---

R/mcmc-diagnostics.R
tests/testthat/_snaps/mcmc-diagnostics/mcmc-neff-missing-levels.svg
tests/testthat/test-mcmc-diagnostics.R

closes #327
Uses `show.legend=TRUE` to make sure legend entries appear even for unobserved levels of rhat and neff.

Fix missing legends for unobserved levels in rhat and neff plots

---

R/ppc-test-statistics.R
man/PPC-test-statistics.Rd
tests/testthat/test-ppc-test-statistics.R

closes #321
Adds section at the very top of the `ppc_stat` documentation (with **NOTE** in bold) that mentions the problem with `stat="mean"`: 
>   **NOTE:** Although the default test statistic is the mean, this is unlikely to detect anything interesting in most cases. In general we recommend using some other test statistic as discussed in Section 5 of Gabry et al. (2019).

Document problems with `ppc_stat` with `stat="mean"`

---

R/mcmc-traces.R
tests/testthat/_snaps/mcmc-traces/mcmc-rank-overlay-not-all-bins.svg
tests/testthat/data-for-mcmc-tests.R
tests/testthat/test-mcmc-traces.R

fixes #331
Code to test: 
```r
x <- posterior::as_draws_array(
list(
list(theta = -2 + 0.003 * 1:1000 + arima.sim(list(ar = 0.7), n = 1000, sd = 0.5)),
list(theta = 1 + -0.01 * 1:1000 + arima.sim(list(ar = 0.7), n = 1000, sd = 0.5))
)
)
bayesplot::mcmc_rank_overlay(x)
```

Ensure rank overlay plot starts at 0 even if not all bins present

---

R/available-module-functions.R
bayesplot.Rproj
tests/testthat/test-available_ppc.R

closes #339
Removes `ppc_loo_pit()` from `available_ppc()` since it's deprecated. I think that's the only one we need to remove for now.

remove deprecated functions from available_ppc()

---

DESCRIPTION
NEWS.md
R/ppc-discrete.R
tests/testthat/_snaps/ppc-discrete/ppc-bars-default.svg
tests/testthat/_snaps/ppc-discrete/ppc-bars-grouped-default.svg
tests/testthat/_snaps/ppc-discrete/ppc-bars-grouped-facet-args-prob-size.svg
tests/testthat/_snaps/ppc-discrete/ppc-bars-prob-0-33-width-size-fatten.svg
tests/testthat/_snaps/ppc-discrete/ppc-bars-width-size-fatten.svg
tests/testthat/test-ppc-discrete.R

Fixes #266.
As explained excellently by @famuvie in #266, `ppc_bars_data()` has been miscounting the summary statistics for `yrep`.
**_This fix would add tidyr as a dependency_**, but as we already have multiply tidyverse packages, I hope this isn't an issue.

Fix missing counts in ppc_bars_data()

---

tests/testthat/test-aesthetics.R
tests/testthat/test-bayesplot_grid.R
tests/testthat/test-mcmc-scatter-and-parcoord.R

Skip some tests when missing Suggests

---

R/ppc-loo.R

In brms it is possible to specify `moment_match = TRUE` in `pp_check`. This is useful for loo functions/plots. This then gets passed to bayesplot `ppc_loo_*` functions and currently throws a warning that `moment_match` is ignored.
This PR adds `"moment_match"` to the `ok_args` in `check_ignored_arguments` for the `ppc_loo_*` functions.

add "moment_match" to ok_args for loo functions
